package JavaGear;

/* This file is autogenerated. Please do not edit manually */
    
public class BuildSettings
{
  public final static String VERSION = "0.97.2";

  public final static boolean ACCURATE = true;
}